# Generated by Django 4.2.7 on 2025-11-26 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(help_text='Campo obrigatório para identificação', max_length=255, verbose_name='Nome do Paciente')),
                ('data_nascimento', models.DateField(help_text='Campo obrigatório para identificação', verbose_name='Data de Nascimento')),
                ('nome_mae', models.CharField(help_text='Campo obrigatório para identificação', max_length=255, verbose_name='Nome da Mãe')),
                ('id_projeto', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID do Projeto')),
                ('id_unico', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Único')),
                ('projeto_original', models.CharField(blank=True, max_length=255, null=True, verbose_name='Projeto Original')),
                ('sexo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sexo')),
                ('rg', models.CharField(blank=True, max_length=50, null=True, verbose_name='RG')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('cid10', models.CharField(blank=True, max_length=10, null=True, verbose_name='CID10')),
                ('data_nascimento_mae', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento da Mãe')),
                ('id_familiar', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Familiar')),
                ('id_lpc_biob', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID LPC BIOB')),
                ('amostra_biologica', models.CharField(blank=True, max_length=255, null=True, verbose_name='Amostra Biológica')),
                ('sangue', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sangue')),
                ('plasma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plasma')),
                ('soro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soro')),
                ('pax_gene', models.CharField(blank=True, max_length=50, null=True, verbose_name='PaxGene')),
                ('saliva', models.CharField(blank=True, max_length=50, null=True, verbose_name='Saliva')),
                ('scu', models.CharField(blank=True, max_length=50, null=True, verbose_name='SCU')),
                ('placenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Placenta')),
                ('placenta_ffpe', models.CharField(blank=True, max_length=50, null=True, verbose_name='Placenta FFPE')),
                ('dna', models.CharField(blank=True, max_length=50, null=True, verbose_name='DNA')),
                ('rna', models.CharField(blank=True, max_length=50, null=True, verbose_name='RNA')),
                ('proteina', models.CharField(blank=True, max_length=50, null=True, verbose_name='Proteína')),
                ('metiloma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Metiloma')),
                ('dnam_gene', models.CharField(blank=True, max_length=50, null=True, verbose_name='DNAm Gene')),
                ('dna_seq', models.CharField(blank=True, max_length=50, null=True, verbose_name='DNA Seq')),
                ('exoma', models.CharField(blank=True, max_length=50, null=True, verbose_name='Exoma')),
                ('rna_seq', models.CharField(blank=True, max_length=50, null=True, verbose_name='RNA Seq')),
                ('mi_rna', models.CharField(blank=True, max_length=50, null=True, verbose_name='miRNA')),
                ('comprimento_telomerico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Comprimento Telomérico')),
                ('citocinas', models.CharField(blank=True, max_length=50, null=True, verbose_name='Citocinas')),
                ('cortisol', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cortisol')),
                ('exossomos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Exossomos')),
                ('prs', models.CharField(blank=True, max_length=50, null=True, verbose_name='PRS')),
                ('outros_bioinfo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Outros (Bioinformática)')),
                ('historico_materno', models.TextField(blank=True, null=True, verbose_name='Histórico Materno')),
                ('historico_gravidez', models.TextField(blank=True, null=True, verbose_name='Histórico de Gravidez')),
                ('historico_familiar', models.TextField(blank=True, null=True, verbose_name='Histórico Familiar')),
                ('info_parto', models.TextField(blank=True, null=True, verbose_name='Informações do Parto')),
                ('cars', models.FloatField(blank=True, null=True, verbose_name='CARS')),
                ('qi', models.FloatField(blank=True, null=True, verbose_name='QI')),
                ('comunicacao_vineland', models.FloatField(blank=True, null=True, verbose_name='Comunicação Vineland')),
                ('hab_dia_vineland', models.FloatField(blank=True, null=True, verbose_name='Hab. Dia a Dia Vineland')),
                ('socializacao_vineland', models.FloatField(blank=True, null=True, verbose_name='Socialização Vineland')),
                ('adi_total', models.FloatField(blank=True, null=True, verbose_name='ADI Total')),
                ('cbcl_internal', models.FloatField(blank=True, null=True, verbose_name='CBCL Internal')),
                ('cbcl_external', models.FloatField(blank=True, null=True, verbose_name='CBCL External')),
                ('score_psiquiatrico_mae', models.FloatField(blank=True, null=True, verbose_name='Score Psiquiátrico Mãe')),
                ('score_exposicao_ambiental', models.FloatField(blank=True, null=True, verbose_name='Score Exposição Ambiental na Gestação')),
                ('score_estresse_materno', models.FloatField(blank=True, null=True, verbose_name='Score Estresse Materno')),
                ('escolaridade_materna', models.FloatField(blank=True, null=True, verbose_name='Escolaridade Materna')),
                ('renda_familiar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Renda Familiar')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('fonte_dados', models.CharField(blank=True, help_text='Origem: Amostras Biológicas, Bioinformática ou Dados Clínicos', max_length=100, null=True, verbose_name='Fonte dos Dados')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-data_cadastro'],
                'indexes': [models.Index(fields=['nome_paciente', 'data_nascimento', 'nome_mae'], name='pacientes_p_nome_pa_e75e44_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConflitoDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=100, verbose_name='Campo em Conflito')),
                ('valor_existente', models.TextField(verbose_name='Valor Existente no Banco')),
                ('valor_novo', models.TextField(verbose_name='Valor Novo a Ser Inserido')),
                ('status', models.CharField(choices=[('novo', 'Novo Conflito'), ('resolvido', 'Resolvido'), ('ignorado', 'Ignorado')], default='novo', max_length=20, verbose_name='Status')),
                ('valor_escolhido', models.TextField(blank=True, null=True, verbose_name='Valor Escolhido')),
                ('data_conflito', models.DateTimeField(auto_now_add=True, verbose_name='Data do Conflito')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('resolvido_por', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resolvido Por')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflitos', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Conflito de Dados',
                'verbose_name_plural': 'Conflitos de Dados',
                'ordering': ['-data_conflito'],
            },
        ),
    ]
