# Generated by Django 4.2.7 on 2025-11-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='adi_total',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ADI Total'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cars',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CARS'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cbcl_external',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CBCL External'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cbcl_internal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CBCL Internal'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='comunicacao_vineland',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comunicação Vineland'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='escolaridade_materna',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Escolaridade Materna'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hab_dia_vineland',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hab. Dia a Dia Vineland'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='qi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='QI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='renda_familiar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Renda Familiar'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='score_estresse_materno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Score Estresse Materno'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='score_exposicao_ambiental',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Score Exposição Ambiental na Gestação'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='score_psiquiatrico_mae',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Score Psiquiátrico Mãe'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='socializacao_vineland',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Socialização Vineland'),
        ),
    ]
