# Generated by Django 4.2.7 on 2025-11-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_adi_total_alter_paciente_cars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id_unico',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True, verbose_name='ID Único'),
        ),
    ]
