# Generated by Django 4.2.7 on 2025-11-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_id_unico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='fonte_dados',
        ),
    ]
